### PR TITLE
James's branch - search question feature

### PR DESCRIPTION
**Pull request by jamesEmerson112**
The list will contain all questions by default, but will have the potential to be filtered to a subset based on user searches (section 1.3.3).

Each answer will start on a new line, where the text body of the answer will display.

### CODE REVIEW

**Review by stolinator — CHANGES_REQUESTED** [review]
👊 👊 Great work V! Please resolve merge conflicts by pulling the latest changes from main!

**Comment by jamesEmerson112** [comment]
Just merged with main. It was strange to see no merge conflicts so far, so could anyone be kind enough to double check?

**Review by nicolastiennguyen — APPROVED** [review]
working against main branch 👍

**Review by stolinator — APPROVED** [review]
Looks good!

Approved!

-Stoli

**Pull request merged**
