### PR TITLE
Indiv question

### PR DESCRIPTION
**Pull request by jamesEmerson112**
Refactoring and some extra css.

This now should be working with everyone's component

### CODE REVIEW

**Review by GoksuOkar — DISMISSED** [review]
-add a close click or button to get out of the question modal without submitting
-submit button logging null when clicked from our click tracker. You can look at it by opening console and clicking submit and you will see.

**Comment by jamesEmerson112** [comment]
> -add a close click or button to get out of the question modal without submitting -submit button logging null when clicked from our click tracker. You can look at it by opening console and clicking submit and you will see.

Yup. Done!

**Comment by jamesEmerson112** [comment]
Possibly final update

**Review by stolinator — APPROVED** [review]
Thank you for committing these changes!

LGTM!

-Stoli

**Comment by jamesEmerson112** [comment]
Nice!

**Pull request merged**
